//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPPDataLayer.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class amenitiesTable
    {
        public int id { get; set; }
        public string amenities { get; set; }
        public string amenitiesSize { get; set; }
        public string maidService { get; set; }
        public int listingID { get; set; }
    }
}
