//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPPDataLayer.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class amenityFee
    {
        public int id { get; set; }
        public string items { get; set; }
        public string fees { get; set; }
        public string feeTypes { get; set; }
        public Nullable<int> listingID { get; set; }
    }
}
