//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPPDataLayer.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class billingsTable
    {
        public int id { get; set; }
        public Nullable<int> planID { get; set; }
        public Nullable<int> listingSize { get; set; }
        public string listingIDs { get; set; }
        public Nullable<int> months { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> promotionCode { get; set; }
        public int ownerID { get; set; }
        public string paymentStatus { get; set; }
        public Nullable<int> order_number { get; set; }
        public string currency_code { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<double> li_0_price { get; set; }
        public Nullable<double> total { get; set; }
        public string credit_card_processed { get; set; }
        public string pay_method { get; set; }
        public string country { get; set; }
        public string ip_country { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string card_holder_name { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public string postalCode { get; set; }
        public string phone { get; set; }
        public string phoneExtension { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Payment_reference_Id { get; set; }
        public string Payment_type { get; set; }
        public Nullable<int> ListingPrice { get; set; }
    }
}
