//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPPDataLayer.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiryTable
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> country { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> arrival { get; set; }
        public Nullable<System.DateTime> departure { get; set; }
        public Nullable<int> adults { get; set; }
        public Nullable<int> children { get; set; }
        public string message { get; set; }
        public int listingID { get; set; }
        public System.DateTime date { get; set; }
    }
}
