//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPPDataLayer.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ownersTable
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string code { get; set; }
        public bool status { get; set; }
        public System.DateTime date { get; set; }
    }
}
