//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPPDataLayer.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ratesTable
    {
        public int id { get; set; }
        public string currency { get; set; }
        public Nullable<int> standardOccupancy { get; set; }
        public Nullable<int> maxOccupancy { get; set; }
        public Nullable<int> extraPersonRate { get; set; }
        public string checkInTime { get; set; }
        public string checkOutTime { get; set; }
        public string paymentOptions { get; set; }
        public string describeRates { get; set; }
        public Nullable<int> listingID { get; set; }
    }
}
