//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPPDataLayer.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviewsTable
    {
        public int id { get; set; }
        public string title { get; set; }
        public string review { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<System.DateTime> arrivalDate { get; set; }
        public int listingID { get; set; }
        public string travelerID { get; set; }
        public bool status { get; set; }
        public System.DateTime date { get; set; }
    }
}
