//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAPPDataLayer.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public int userid { get; set; }
        public string loginid { get; set; }
        public string password { get; set; }
        public string roal { get; set; }
        public int status { get; set; }
    }
}
